### ISSUE TITLE
Different Dice score for BraTS2018 dataset

### ISSUE THREAD

**Issue by DTA-lab** [cuttle-fish-my/GM-Guided-DG#1]
Hey !!
          i have run the code with BraTS2018 dataset, the dice score is low than you claimed, i will attach the picture for reference. 
The dice score that you have claimed (T2-T1) is 0.6793 but the dice score i got  (T2-T1) is 0.5554 and same for the others you can check the attached file. Looking forward for your response

(https://github.com/cuttle-fish-my/GM-Guided-DG/assets/153801064/c0809caf-6b13-4341-9724-ae775b5690b7)

**Comment by DTA-lab** [comment]
![Screenshot from 2024-02-23 15-06-04](https://github.com/cuttle-fish-my/GM-Guided-DG/assets/153801064/e0eac953-5a88-4ed8-869c-986e59553ba8)

**Comment by cuttle-fish-my** [comment]
Thanks for your interest! Did you use the pre-trained model provided in google drive or the one trained from scratch? If you trained from scratch, what train config did you used?

**Comment by DTA-lab** [comment]
> Thanks for your interest! Did you use the pre-trained model provided in google drive or the one trained from scratch? If you trained from scratch, what train config did you used?

I have trained from scratch, and i have use the same configuration as in the git hub

**Comment by DTA-lab** [comment]
> > Thanks for your interest! Did you use the pre-trained model provided in google drive or the one trained from scratch? If you trained from scratch, what train config did you used?
> 
> I have trained from scratch, and i have use the same configuration as in the git hub

config : 

TRAIN_FLAGS="--data_dir ../datasets/BraTS_2018_flair2t1/train
            --use_fp16 True
            --save_dir ../saved_models/BraTS/flair/GMGDG
            --lr 1e-4
            --batch_size 24
            --save_interval 1000
            --lr_anneal_steps 10000
            --modality source
            --input_mode magnitude
            --in_channels 3
            --heavy_aug True
            --norm_type BN"



python ../src/Unet_train.py $TRAIN_FLAGS

**Comment by cuttle-fish-my** [comment]
> ![Screenshot from 2024-02-23 15-06-04](https://private-user-images.githubusercontent.com/153801064/307256460-e0eac953-5a88-4ed8-869c-986e59553ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTM4NjEsIm5iZiI6MTcwOTAxMzU2MSwicGF0aCI6Ii8xNTM4MDEwNjQvMzA3MjU2NDYwLWUwZWFjOTUzLTVhODgtNGVkOC04NjljLTk4NmU1OTU1M2JhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwNTU5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzNmYWU3YjNjNmI2NjhlMjNmMGUwMzNmNTExMmQyNzNmN2NjYmE2YTBiMTdlMTdkZDdmY2VkM2UxNjUwNDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TbjDYwe3iznOtplL1APLgBPFvO-QN73CuGgGDKc1A0Q)

Ohhh! I see, it seems I forgot to set the TTA config in the test scripts, which leads to `TTA mode: None` in your screenshot, I've fixed this in 72ee40f! Thanks for your feedback!
